//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Qty_In_Hand { get; set; }
        public Nullable<int> Qty_Sold { get; set; }
        public Nullable<decimal> ItemWholeSalePrice { get; set; }
        public Nullable<decimal> ItemRetailPrice { get; set; }
        public Nullable<decimal> Vendor_Price { get; set; }
        public Nullable<decimal> Last_Purchased_Price { get; set; }
        public Nullable<int> ReOrderLevel { get; set; }
        public Nullable<int> ReOrderQty { get; set; }
        public Nullable<System.DateTime> PriceLastUpdated { get; set; }
    }
}
