//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.Purchase_Details = new HashSet<Purchase_Details>();
        }
    
        public int Purchase_ID { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<decimal> TotalVAT { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Lot_No1 { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual ICollection<Purchase_Details> Purchase_Details { get; set; }
    }
}
