//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Details
    {
        public int P_Detail_ID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> VendorRate { get; set; }
        public Nullable<decimal> FinalRate { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> Purchase_ID { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
